import {SiteLocale} from "@/lib/site-locale";

export interface RegionalSeo {
    region: string;
    countryCode: string;
    ogLocale: string;
    keywords: string[];
    blogTitle: string;
    blogDescription: string;
}

const REGIONAL_SEO: Record<SiteLocale, RegionalSeo> = {
    en: {
        region: "Worldwide",
        countryCode: "001",
        ogLocale: "en_US",
        keywords: [
            "global website development company",
            "international web design agency",
            "website development company India",
            "web design India",
            "SEO services worldwide",
            "technical SEO agency",
            "mobile app development company",
            "SaaS development company",
            "digital marketing agency worldwide",
            "website design and development company",
            "custom website development services",
            "website development for small businesses",
            "website development for startups",
            "SEO-friendly website development",
            "responsive website development services",
            "website redesign services",
            "ecommerce website development",
            "WordPress website development",
            "web application development company",
            "website development cost",
            "website development company near me",
            "best website development company",
            "top website development company",
            "website development company USA",
            "website development company California",
            "website development company UK",
            "website development company Japan",
            "website development company Tokyo",
            "website development company South Africa",
            "website development company Australia",
            "website development company Canada",
            "website development company UAE",
            "website development company Singapore",
            "website development company New Zealand",
            "website development company Ireland",
            "website development company Germany",
            "website development company France",
            "website development company Italy",
            "website development company Spain",
            "website development company Netherlands",
            "website development company Sweden",
            "website development company Switzerland",
            "website development company Brazil",
            "website development company Mexico",
            "website development company Argentina",
            "website development company Nigeria",
            "website development company Kenya",
            "website development company Egypt",
            "website development company Saudi Arabia",
            "website development company Qatar",
            "website development company Malaysia",
            "website development company Indonesia",
            "website development company Thailand",
            "website development company Vietnam",
            "website development company Philippines",
            "website development company South Korea",
            "website development company Hong Kong",
            "SaaS development company",
            "SaaS application development",
            "web application development company",
            "mobile app development company",
            "Flutter app development",
            "Kotlin app development",
            "Android app development",
            "iOS app development",
            "Node.js development company",
            "React.js development company",
            "Next.js development company",
            "Laravel development company",
            "Shopify development company",
            "MongoDB application development",
            "AWS cloud development",
            "Google Cloud development",
            "Docker deployment services",
            "DevOps development services",
            "SEO services for websites",
            "digital marketing services",
            "technical SEO services",
            "AI application development",
            "OpenAI integration services",
            "ChatGPT integration services",
            "Claude AI integration",
            "n8n automation services",
            "generative AI development company",
            "AI automation services",
            "Figma UI UX design",
            "Adobe XD UI UX design",
            "UI UX design and development",
            "Git and GitHub development workflow",
            "Bitbucket development workflow",
            "PHP web development",
            "Python web development",
            "Java application development",
            ".NET application development",
            "Vue.js development company",
            "Angular development company",
            "TypeScript development company",
            "PostgreSQL application development",
            "Firebase application development",
            "Supabase application development",
            "Kubernetes deployment services",
            "Azure cloud development",
            "Google Cloud Platform development",
            "Vercel deployment services",
            "API integration services",
            "backend development company",
            "frontend development company",
            "full stack development company",
            "user interface design",
            "conversion rate optimisation",
            "conversion rate optimization",
            "UI UX designing",
            "UX design and UI design",
            "digital marketing agency India",
            "digital marketing firms in India",
            "digital advertising companies in India",
            "India SEO company",
            "Indian SEO agency",
            "SEO firms India",
            "India SEO firm",
            "SEO company from India",
            "SEO provider in India",
            "search engine optimization companies in India",
            "search engine optimization agency in India",
            "web programming company",
            "development website company",
            "digital marketing business in India",
            "mobile app designing company",
            "digital marketing agency Delhi",
            "digital marketing company in Delhi",
            "Delhi digital marketing company",
            "digital marketing agency Delhi NCR",
            "digital marketing company in Delhi NCR",
            "digital marketing agency Bangalore",
            "digital marketing companies in Bangalore",
            "web development company in Bangalore",
            "website development company Bangalore",
            "website design company in Bangalore",
            "website development Bangalore",
            "web development Bangalore",
            "digital marketing agency Ahmedabad",
            "digital marketing company in Ahmedabad",
            "SEO agency Mumbai",
            "SEO companies Mumbai",
        ],
        blogTitle: "Web Design & SEO Blog | Adamant",
        blogDescription: "Practical insights on website development, UX, technical SEO, SaaS and digital marketing for businesses worldwide.",
    },
    "en-us": {
        region: "United States",
        countryCode: "US",
        ogLocale: "en_US",
        keywords: [
            "website development company USA",
            "best website development company USA",
            "top website development companies USA",
            "top 10 website development companies USA",
            "website design and development company USA",
            "custom website development services USA",
            "website development for small businesses USA",
            "website development for startups USA",
            "web design USA",
            "technical SEO USA",
            "SaaS development USA",
            "digital marketing USA",
            "website development company in California",
            "website development company in Los Angeles",
            "website development company in San Francisco",
        ],
        blogTitle: "Web Design & SEO Blog (USA) | Adamant",
        blogDescription: "Website, UX, technical SEO, SaaS and digital marketing insights for startups and growing businesses in the United States.",
    },
    hi: {
        region: "India",
        countryCode: "IN",
        ogLocale: "hi_IN",
        keywords: ["वेबसाइट डेवलपमेंट कंपनी भारत", "वेब डिजाइन भारत", "SEO सेवाएं भारत", "मोबाइल ऐप डेवलपमेंट", "डिजिटल मार्केटिंग भारत"],
        blogTitle: "वेबसाइट और SEO ब्लॉग | Adamant",
        blogDescription: "भारत के व्यवसायों के लिए वेबसाइट डेवलपमेंट, UX, तकनीकी SEO, SaaS और डिजिटल मार्केटिंग पर व्यावहारिक जानकारी।",
    },
    gu: {
        region: "India",
        countryCode: "IN",
        ogLocale: "gu_IN",
        keywords: ["વેબસાઇટ ડેવલપમેન્ટ કંપની ભારત", "વેબ ડિઝાઇન ગુજરાત", "SEO સેવાઓ ભારત", "મોબાઇલ એપ ડેવલપમેન્ટ", "ડિજિટલ માર્કેટિંગ ભારત"],
        blogTitle: "વેબ ડિઝાઇન અને SEO બ્લોગ | Adamant",
        blogDescription: "ભારતના વ્યવસાયો માટે વેબસાઇટ ડેવલપમેન્ટ, UX, ટેક્નિકલ SEO, SaaS અને ડિજિટલ માર્કેટિંગ અંગે ઉપયોગી માહિતી.",
    },
    mr: {
        region: "India",
        countryCode: "IN",
        ogLocale: "mr_IN",
        keywords: ["वेबसाइट डेव्हलपमेंट कंपनी भारत", "वेब डिझाइन महाराष्ट्र", "SEO सेवा भारत", "मोबाइल अॅप डेव्हलपमेंट", "डिजिटल मार्केटिंग भारत"],
        blogTitle: "वेब डिझाइन आणि SEO ब्लॉग | Adamant",
        blogDescription: "भारतामधील व्यवसायांसाठी वेबसाइट डेव्हलपमेंट, UX, तांत्रिक SEO, SaaS आणि डिजिटल मार्केटिंगविषयी उपयुक्त माहिती.",
    },
    bn: {
        region: "India",
        countryCode: "IN",
        ogLocale: "bn_IN",
        keywords: ["ওয়েবসাইট ডেভেলপমেন্ট কোম্পানি ভারত", "ওয়েব ডিজাইন ভারত", "SEO পরিষেবা ভারত", "মোবাইল অ্যাপ ডেভেলপমেন্ট", "ডিজিটাল মার্কেটিং ভারত"],
        blogTitle: "ওয়েব ডিজাইন ও SEO ব্লগ | Adamant",
        blogDescription: "ভারতের ব্যবসার জন্য ওয়েবসাইট ডেভেলপমেন্ট, UX, টেকনিক্যাল SEO, SaaS এবং ডিজিটাল মার্কেটিং সম্পর্কে ব্যবহারিক তথ্য।",
    },
    ta: {
        region: "India",
        countryCode: "IN",
        ogLocale: "ta_IN",
        keywords: ["வலைத்தள மேம்பாட்டு நிறுவனம் இந்தியா", "வலை வடிவமைப்பு இந்தியா", "SEO சேவைகள் இந்தியா", "மொபைல் ஆப் மேம்பாடு", "டிஜிட்டல் மார்க்கெட்டிங் இந்தியா"],
        blogTitle: "இணைய வடிவமைப்பு மற்றும் SEO | Adamant",
        blogDescription: "இந்திய நிறுவனங்களுக்கான வலைத்தள மேம்பாடு, UX, தொழில்நுட்ப SEO, SaaS மற்றும் டிஜிட்டல் மார்க்கெட்டிங் குறிப்புகள்.",
    },
    es: {
        region: "Spanish-speaking markets",
        countryCode: "ES",
        ogLocale: "es_ES",
        keywords: ["empresa de desarrollo web", "diseño web y SEO", "desarrollo de aplicaciones móviles", "desarrollo SaaS", "marketing digital"],
        blogTitle: "Blog de diseño web y SEO | Adamant",
        blogDescription: "Ideas prácticas sobre desarrollo web, UX, SEO técnico, SaaS y marketing digital para empresas de mercados hispanohablantes.",
    },
    fr: {
        region: "French-speaking markets",
        countryCode: "FR",
        ogLocale: "fr_FR",
        keywords: ["agence de développement web", "création site internet SEO", "développement application mobile", "développement SaaS", "marketing digital"],
        blogTitle: "Blog design web et SEO | Adamant",
        blogDescription: "Conseils pratiques sur le développement web, l'UX, le SEO technique, le SaaS et le marketing digital pour les entreprises francophones.",
    },
    de: {
        region: "German-speaking markets",
        countryCode: "DE",
        ogLocale: "de_DE",
        keywords: ["Webentwicklung Agentur", "Webdesign und SEO", "App Entwicklung", "SaaS Entwicklung", "digitales Marketing"],
        blogTitle: "Webdesign & SEO Blog | Adamant",
        blogDescription: "Praxisnahe Einblicke in Webentwicklung, UX, technisches SEO, SaaS und digitales Marketing für deutschsprachige Unternehmen.",
    },
    "de-ch": {
        region: "Switzerland",
        countryCode: "CH",
        ogLocale: "de_CH",
        keywords: ["Webentwicklung Schweiz", "Webdesign Schweiz", "SEO Agentur Schweiz", "App Entwicklung Schweiz", "digitales Marketing Schweiz"],
        blogTitle: "Web & SEO Blog Schweiz | Adamant",
        blogDescription: "Einblicke in Webentwicklung, UX, technisches SEO, SaaS und digitales Marketing für Schweizer Unternehmen.",
    },
    "fr-ch": {
        region: "French-speaking Switzerland",
        countryCode: "CH",
        ogLocale: "fr_CH",
        keywords: ["développement web Suisse", "création site web Suisse", "agence SEO Suisse", "application mobile Suisse", "marketing digital Suisse"],
        blogTitle: "Blog web et SEO Suisse | Adamant",
        blogDescription: "Conseils sur le développement web, l'UX, le SEO technique, le SaaS et le marketing digital pour les entreprises suisses francophones.",
    },
    "it-ch": {
        region: "Italian-speaking Switzerland",
        countryCode: "CH",
        ogLocale: "it_CH",
        keywords: ["sviluppo web Svizzera", "web design Svizzera", "agenzia SEO Svizzera", "sviluppo app Svizzera", "marketing digitale Svizzera"],
        blogTitle: "Blog web e SEO Svizzera | Adamant",
        blogDescription: "Approfondimenti su sviluppo web, UX, SEO tecnica, SaaS e marketing digitale per le aziende della Svizzera italiana.",
    },
    pt: {
        region: "Portuguese-speaking markets",
        countryCode: "PT",
        ogLocale: "pt_PT",
        keywords: ["empresa de desenvolvimento web", "design web e SEO", "desenvolvimento de aplicações móveis", "desenvolvimento SaaS", "marketing digital"],
        blogTitle: "Blog de web design e SEO | Adamant",
        blogDescription: "Conteúdos práticos sobre desenvolvimento web, UX, SEO técnico, SaaS e marketing digital para empresas lusófonas.",
    },
    ja: {
        region: "Japan",
        countryCode: "JP",
        ogLocale: "ja_JP",
        keywords: ["Webサイト制作 日本", "ホームページ制作 SEO", "アプリ開発 日本", "SaaS開発", "デジタルマーケティング"],
        blogTitle: "Web制作・SEOブログ | Adamant",
        blogDescription: "日本企業向けのWebサイト制作、UX、テクニカルSEO、SaaS、デジタルマーケティングに関する実践的な情報。",
    },
    ko: {
        region: "South Korea",
        countryCode: "KR",
        ogLocale: "ko_KR",
        keywords: ["웹사이트 개발 회사", "웹디자인 SEO", "앱 개발 한국", "SaaS 개발", "디지털 마케팅"],
        blogTitle: "웹사이트·SEO 블로그 | Adamant",
        blogDescription: "한국 기업을 위한 웹사이트 개발, UX, 기술 SEO, SaaS 및 디지털 마케팅 실무 인사이트.",
    },
    ar: {
        region: "United Arab Emirates and Arabic-speaking markets",
        countryCode: "AE",
        ogLocale: "ar_AE",
        keywords: ["شركة تصميم مواقع", "تطوير المواقع في الإمارات", "تحسين محركات البحث", "تطوير تطبيقات الجوال", "التسويق الرقمي"],
        blogTitle: "مدونة تصميم المواقع وSEO | Adamant",
        blogDescription: "رؤى عملية حول تطوير المواقع وتجربة المستخدم وSEO التقني ومنتجات SaaS والتسويق الرقمي للشركات العربية.",
    },
    "zh-cn": {
        region: "China",
        countryCode: "CN",
        ogLocale: "zh_CN",
        keywords: ["中国网站开发公司", "中国网站建设", "中文SEO", "中国移动应用开发", "SaaS开发中国", "中国数字营销"],
        blogTitle: "网站开发与 SEO 博客 | Adamant",
        blogDescription: "面向中国企业的网站开发、用户体验、技术 SEO、SaaS 产品和数字营销实用内容。",
    },
};

export function getRegionalSeo(locale: SiteLocale) {
    return REGIONAL_SEO[locale];
}
