"use client";

import {Check, Database, Mail, MessageCircle, Moon, Sun, Laptop} from "lucide-react";
import {PageHeader} from "@/components/admin/admin-ui";
import {useAdminTheme} from "@/components/admin/admin-theme-provider";

export function SettingsScreen() {
    const {theme, setTheme} = useAdminTheme();
    return <div className="mx-auto max-w-4xl space-y-5"><PageHeader title="Settings" description="Workspace preferences and integration readiness."/><section className="crm-card p-5 sm:p-6"><h2 className="text-sm font-semibold">Appearance</h2><p className="mt-1 text-[11px] text-[var(--crm-muted)]">Choose how the CRM looks on this device.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{([{id: "light", label: "Light", icon: Sun}, {id: "dark", label: "Dark", icon: Moon}, {id: "system", label: "System", icon: Laptop}] as const).map((option) => { const Icon = option.icon; return <button key={option.id} onClick={() => setTheme(option.id)} className={`flex items-center gap-3 rounded-lg border p-3 text-left transition ${theme === option.id ? "border-[#0d5c63] bg-[#eaf3f2] text-[#0d5c63]" : "border-[var(--crm-border)] bg-[var(--crm-surface)] hover:bg-[var(--crm-subtle)]"}`}><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-current/15"><Icon className="h-4 w-4"/></span><span className="text-xs font-semibold">{option.label}</span>{theme === option.id ? <Check className="ml-auto h-4 w-4"/> : null}</button>; })}</div></section><section className="crm-card overflow-hidden"><div className="border-b border-[var(--crm-border)] p-5 sm:p-6"><h2 className="text-sm font-semibold">Connections</h2><p className="mt-1 text-[11px] text-[var(--crm-muted)]">Phase 1 uses Supabase only. Other channels are intentionally not connected yet.</p></div><div className="divide-y divide-[var(--crm-border)]"><Connection icon={<Database className="h-4 w-4"/>} name="Supabase" description="Authentication, PostgreSQL data and RLS" status="Connected" active/><Connection icon={<MessageCircle className="h-4 w-4"/>} name="WhatsApp Business" description="Planned via Meta Cloud API and webhooks" status="Future phase"/><Connection icon={<Mail className="h-4 w-4"/>} name="Email and lead channels" description="Instagram, LinkedIn and email ingestion" status="Future phase"/></div></section></div>;
}

function Connection({icon, name, description, status, active = false}: {icon: React.ReactNode; name: string; description: string; status: string; active?: boolean}) { return <div className="flex items-center gap-3 p-4 sm:px-6"><span className="flex h-9 w-9 items-center justify-center rounded-lg border border-[var(--crm-border)] bg-[var(--crm-subtle)] text-[var(--crm-muted)]">{icon}</span><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{name}</p><p className="mt-0.5 text-[10px] text-[var(--crm-muted)]">{description}</p></div><span className={`rounded-md px-2 py-1 text-[10px] font-semibold ${active ? "bg-emerald-50 text-emerald-700" : "bg-[var(--crm-subtle)] text-[var(--crm-muted)]"}`}>{status}</span></div>; }
